# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Global variables
# WinRM configuration for communicating with the guest
WINRM_HOST_PORT = 5895
WINRM_PASSWORD = "FooBarBaz"

# Host setup
HOSTNAME = "webserver01"
# IP address has to be from its own subnet
IP_ADDRESS = "10.0.0.30"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "sample-app-appbox"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  # Create a private network on the specified ip address and hostname
  config.vm.network "private_network", ip: IP_ADDRESS
  # Wont work until get vbox working with router
  # config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = HOSTNAME

  # Configure port forwarding 
  config.vm.network :forwarded_port,   guest: 3389, host: 3399,       id: "rdp",   auto_correct: false
  config.vm.network :forwarded_port,   guest: 5985, host: WINRM_HOST_PORT,  id: "winrm", auto_correct: false
  config.vm.network :forwarded_port,   guest: 80,   host: 8000,       id: "web" # Port forward for IIS
  config.vm.network :forwarded_port,   guest: 443,  host: 8443,       id: "ssl" # Port forward for SSL IIS
  config.vm.network :forwarded_port,   guest: 4018, host: 4018,       id: "remotevsdebug"

  # Configure winrm
  config.winrm.host = "localhost"
  config.winrm.password = WINRM_PASSWORD
  config.winrm.port = WINRM_HOST_PORT
  config.winrm.guest_port = WINRM_HOST_PORT

  # GUI or headless
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
